/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCInterface */

#ifndef _Included_JavaCInterface
#define _Included_JavaCInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCInterface
 * Method:    SetupCSide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_SetupCSide
  (JNIEnv *, jobject);

/*
 * Class:     JavaCInterface
 * Method:    FreeCSide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_FreeCSide
  (JNIEnv *, jobject);

/*
 * Class:     JavaCInterface
 * Method:    DrawVolumeSlice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawVolumeSlice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    DrawVolumeCrop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawVolumeCrop
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    DrawMiniture3D
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawMiniture3D
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    DrawRegionSlice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawRegionSlice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    DrawRegion3D
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawRegion3D
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    Draw3DModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_Draw3DModel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    DrawProgressBar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_DrawProgressBar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    MousePressed
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_MousePressed
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    MouseReleased
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_MouseReleased
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    MouseDragged
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_MouseDragged
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    LoadVolumeFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadVolumeFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaCInterface
 * Method:    LoadFloatVolumeFile
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadFloatVolumeFile
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    LoadMinitureFile
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadMinitureFile
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     JavaCInterface
 * Method:    LoadMiniturePointStructureFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadMiniturePointStructureFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaCInterface
 * Method:    LoadMeshFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadMeshFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaCInterface
 * Method:    LoadTextureFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_LoadTextureFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaCInterface
 * Method:    GetVolumeDimensions
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JavaCInterface_GetVolumeDimensions
  (JNIEnv *, jobject);

/*
 * Class:     JavaCInterface
 * Method:    LoadVolumeSlice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_LoadVolumeSlice
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaCInterface
 * Method:    AutoIntensity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_AutoIntensity
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaCInterface
 * Method:    SetVolumeIntensity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_SetVolumeIntensity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     JavaCInterface
 * Method:    SetPointStructureIntensity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_SetPointStructureIntensity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     JavaCInterface
 * Method:    SetPointStructure
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_SetPointStructure
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaCInterface
 * Method:    ResetVolumeCropRegion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCInterface_ResetVolumeCropRegion
  (JNIEnv *, jobject);

/*
 * Class:     JavaCInterface
 * Method:    SaveNewProject
 * Signature: (Ljava/lang/String;IILjava/lang/String;FLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaCInterface_SaveNewProject
  (JNIEnv *, jobject, jstring, jint, jint, jstring, jfloat, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

void RedrawJavaSide();
void JavaSetVolumeIntensity( float minimum, float maximum );
void JavaSetCropRegion( int minx, int maxx, int miny, int maxy, int minz, int maxz );
void JavaSetPointStructureIntensity( float minimum, float maximum );
void JavaSetIntensityLabel( float minimum, float maximum, int data[] );
